### ISSUE TITLE
Example of OAuth Slack App

### ISSUE THREAD

**Issue by emorydunn** [pvzig/SlackKit#118]
I've been building a very basic app with SlackKit, and I'm having some trouble figuring out what the "correct" way to have multiple workspaces authenticate. Following the example for the ready-to-launch app using OAuth I can get multiple authorizations, but the newest one overwrites the previous one's WebAPI and RTM connections (I get an error when sending a message that the channel doesn't exist). 

I'm also wondering what the best way to re-establish connections is. The only way I've been able to successfully get everything to work is to create a new instance of SlackKit for each auth token.

**Comment by pvzig** [comment]
Hey Emory,

I'd never tested anything with multiple workspaces so that's definitely a bug you're hitting. I'll need to take a look at supporting that.

RTM should reconnect automatically if it's dropped at any point, but if your server goes down you would need to be storing the tokens and reinitializing SlackKit instances.

If you have fixes for any of these issues I'm happy to merge PRs.

**Comment by emorydunn** [comment]
I'm working on some changes now that so far seem to be working. The basic idea is to replace the values of the `SlackKit.clients` dictionary with a class that holds and RTM and WebAPI connections for each client.

**Comment by pvzig** [comment]
This is resolved with: https://github.com/SlackKit/SlackKit/pull/121
