### ISSUE TITLE
Any problems running latest Swift 3 version on iOS 10 device?

### ISSUE THREAD

**Issue by davidahouse** [pvzig/SlackKit#55]
I'm having nothing but trouble getting it to run on my device without crashing with bad access violations. Debugging this in Xcode 8 really isn't providing much to go on. Just want to confirm that it does work for others in Xcode 8 / Swift 3 project.

![event_swift_and_new_issue_ _pvzig_slackkit](https://cloud.githubusercontent.com/assets/140127/19411636/548b3c72-92d3-11e6-9b18-a8d565a00033.png)

This happens literally with just creating the SlackKit object with an API token. Looks like it can't process the initial messages from Slack. But not sure why.

Related note: Carthage build will not work for me either, so I pulled in the 3 projects into a workspace and am letting it build each that way. Seems to build ok, but just this weird on device issue (works ok in simulator).

**Comment by pvzig** [comment]
Just wanted to follow up and say that I've replicated this as well on-device and that it seems to be a memory allocation issue related to Swift. I'm working on tracking down the root issue and will push a fix ASAP.

Re: Carthage, the problem is that SlackKit takes a long, long time (>3 hrs!) to compile with optimizations turned on in the `Release` configuration. This is something else I'm working on a fix for, but in the meantime you can specify the `Debug` configuration like so: `carthage bootstrap --configuration "Debug"`

**Comment by davidahouse** [comment]
Thanks! Will look for a fix, but also interested in why this is happening. Might not even be a problem in the SlackKit code directly, but in the dependencies.

**Comment by ghost** [comment]
same problem for me : works OK on simulator, but crash on device ...

**Comment by pvzig** [comment]
Long story short, it was a memory leak from using a value type when I needed a reference type. Should be fixed in [3.1.5](https://github.com/pvzig/SlackKit/releases/tag/3.1.5).
