### ISSUE TITLE
I had to lower optimization to none to get Xcode 7.2 and swift 2.1.1

### ISSUE THREAD

**Issue by tomandersen** [pvzig/SlackKit#7]
Otherwise Xcode just hung trying to compile. Perhaps this will go away when shipping Xcode is Swift 2.2

**Comment by pvzig** [comment]
It doesn't actually fail, it just takes a _long_ time. It looks like Swift 2.2 speeds things up considerably on this front, and since you're usually going to be compiling as `[-Onone]` when you're developing, I think this is suboptimal but fine. That said, I'll take a look at breaking up `EventDispatcher.swift` and `EventHandler.swift` as those seem to be the files the compiler is struggling with to see if I can generate any meaningful compilation speed increases.

Compile times on a 2.8 GHz Dual Core Intel Core i7:

## Swift 2.1.1, Xcode 7.2

Fast `[-O]`: ~14 minute compile time
Fast, Whole Module Optimization `[-O -whole-module-optimization]`: ~14 minute compile time

## swift-2.2-SNAPSHOT-2016-01-11, Xcode 7.2

Fast `[-O]`: ~4 minute compile time
Fast, Whole Module Optimization `[-O -whole-module-optimization]`: ~4 minute compile time

**Comment by tomandersen** [comment]
Thanks. I guess I don't have the patience for that swift compiler yet! Those files are not even that long, and they don't look complicated either.
