### ISSUE TITLE
SlackKit with concurrent HTTPServer usage

### ISSUE THREAD

**Issue by JacopoMangiavacchi** [pvzig/SlackKit#71]
Hi Peter,

I'm working on a Slack bot sample project using your super SlackKit package from the linux branch.  The thing is that my project, other than managing the websocket connection with SlackKit, it also need to expose a Rest Api.

I'm trying to use Zewo for the web server and basically using SlackClient and HTTPServer on two different dispatch queue but I'm always getting a Segmentation fault 11 error.

I had to fork your SlackKit repo and rename the SlackKit Message class as SlackMessage because of a conflict with Zero Message class.

Debugging I can see the crash is on CLibVenice library on releasing a probably not available autoreleasepool.

I've tried to add an autoreleasepool on the background queue but the problem persist.  Any hint on this ?

If you want to take a look at the code both SlackKit fork and Bot sample are on my git repo:

- https://github.com/JacopoMangiavacchi/SlackKit
- https://github.com/JacopoMangiavacchi/SlackWebhookGateway

Thanks a lot,
Jacopo

**Comment by pvzig** [comment]
Hi Jacopo,

The crashes you're seeing are because you're using GCD with libraries that aren't thread safe. The linux branch of SlackKit uses https://github.com/Zewo/WebSocketClient, and the [Zewo HTTPServer](https://github.com/Zewo/HTTPServer) you're using both use [Venice](https://github.com/Zewo/Venice), a CSP-style concurrency library. There is a good high level explanation [here](https://github.com/Zewo/Zewo#what-sets-zewo-apart).

Here's a simple example of how it might look using coroutines: https://gist.github.com/pvzig/20048544a853e0ab81aed9c8ba452943#file-slackwebhookgateway-swift-L14

Peter

**Comment by pvzig** [comment]
Also, to get around the namespace conflict you can use `SlackKit.Message` in place of `Message` as the type to let the compiler know which you mean.

**Comment by JacopoMangiavacchi** [comment]
Thank you very much Peter
