### ISSUE TITLE
Autocomplete / lldb debugging not working

### ISSUE THREAD

**Issue by joeldrotleff** [pvzig/SlackKit#78]
I'm having some issue with debugging using SlackKit.

If I create a simple project using Swift package manager, setting SlackKit as a dependency, I can compile / run the project with no issues, but autocomplete is broken. For example within the private func handleMessage(message: Message) method, "message" autocompletes to <<error type>>.

I also notice that if I put a breakpoint in that same method, none of the local variables are shown in the debugger, and if I try to po some of them it gives a bunch of warnings like this:

 warning: Swift error in module robot-or-not-bot.
Debug info from this module will be unavailable in the debugger.

**Comment by pvzig** [comment]
Hey Joel,

I think this is a SPM [bug](https://bugs.swift.org/browse/SR-3121) which has recently been [fixed](https://github.com/apple/swift-package-manager/pull/907). If you're willing to use a development keychain it looks to be fixed in [swift-3.1-DEVELOPMENT-SNAPSHOT-2017-01-31](https://swift.org/builds/swift-3.1-branch/xcode/swift-3.1-DEVELOPMENT-SNAPSHOT-2017-01-31-a/swift-3.1-DEVELOPMENT-SNAPSHOT-2017-01-31-a-osx.pkg). A `.xcodeproj` file generated as follows should work:

1. Set your default keychain:
`$ export PATH=/Library/Developer/Toolchains/swift-3.1-DEVELOPMENT-SNAPSHOT-2017-01-31-a.xctoolchain/usr/bin:"${PATH}"`
2. `swift package generate-xcodeproj`
