### ISSUE TITLE
Can't get client to connect...

### ISSUE THREAD

**Issue by sirvon** [pvzig/SlackKit#80]
Here's my code to start a RTM connection as per readme:

```swift
....
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate,MessageEventsDelegate {
...
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
....
        let options = ClientOptions(pingInterval: 2, timeout: 5, reconnect: true)
        let bot = SlackKit(withAPIToken:xoxp-xxxxxxxxx,clientOptions: options)
        bot.onClientInitalization = { (client: Client) in
            print(client)
            print(client.connected)
            DispatchQueue.main.async(execute: {
                client.messageEventsDelegate = self
            })
        }
        print(bot)
.....
    // MARK: MessageEventsDelegate
    func received(_ message: Message, client: Client) {
        print(message)
    }
    
    func connected(_ client: Client) {
        print(client)
    }
```

client.connected is always returning false
what gives?

edit: ok I got the above code to work by adding this ```client.connect()```
in the onClientInit block....
and it prints in the received func the last received msg....
but How do i receive all subsequent messages while the client is connected?

**Comment by pvzig** [comment]
Hi Sirvon,

Your `SlackKit` instance is being released because you've only declared it in the local scope of the `application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool` function.

Moving it into global state will prevent it from being released until `AppDelegate` is released.

```
let bot = SlackKit(withAPIToken:xoxp-xxxxxxxxx, clientOptions: options)

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    ...
}
```

The [Leaderboard example](https://github.com/pvzig/SlackKit-examples) is a good reference for what a basic SlackKit app looks like.
